# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20161209_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url, shortner.validators.validate_dot_com]),
        ),
    ]
